### ISSUE TITLE
Share TransferFunc Color

### ISSUE THREAD

**Issue by engineer1109** [terier/vpt#2]
I alway found that the color renderred is too dark or not competitable

**Comment by CirilBohak** [comment]
I am not sure what do mean by "too dark".  There are three main factors that define this:
- The extinction coefficient, which defines how deep the light will actually penetrate into the material. Currently, only a single extinction coefficient is supported by the system but can be further affected by the transparency of the blob in the transfer function.
- It also helps if you set the scattering bias towards the viewer. While the result is biased, it will get brighter sooner.
- This is also affected by the number of bounces you simulate in the medium (due to Russian roulette implementation, you can easily tune it up, without big impact on the performance)
- You can increase the brightness of the environmental contribution
- You can adjust the levels in the postprocessing using Tone mapper
