### ISSUE TITLE
Add diffuse gradient and specular reflection to multi-scattering?

### ISSUE THREAD

**Issue by engineer1109** [terier/vpt#3]
I found that multi-scattering is not with gradients. (EM also)
If an object is all the same pixel value, it will be rendered with same color.

**Comment by engineer1109** [comment]
It should be called BRDF or BRSF?

**Comment by CirilBohak** [comment]
Both Multiple scattering and EAM do support gradients. You can see this in the function sampleVolumeColor, where rg is sampled. r - value, g - gradient. You do need appropriate data. The gradients are not calculated on the fly, they must be bundled with the data ... this is where the BVP format we are using comes in handy.

Specular reflections? This is volumetric path tracing, and reflections are there and are the results of the process itself.

We do not have any support for BRDF or BSDF (I guess you mistyped BRSF), since we are not doing surface rendering. There is an anisotropic phase function used in the rendering.

**Comment by engineer1109** [comment]
@CirilBohak ![image](https://github.com/engineer1109/VolumeRenderPhotos/blob/main/photos/test1.png?raw=true)

See
https://github.com/engineer1109/VolumeRenderPhotos/blob/main/photos
Volume Renders can also have reflections. BRDF is also supported for volume render.

**Comment by CirilBohak** [comment]
Of course, you can have specular reflections in case you present.

However, as I said VPT only supports isotropic phase functions and not BRDFS. When one uses BRDFs one needs to assume there are surfaces in the volume. We do not assume this. You can check also the work of Kroes et al. [Exposure render: an interactive photo-realistic volume rendering framework](https://graphics.tudelft.nl/Publications-new/2012/KPB12a/Kroes2011.pdf).

We do plan to add such support at some point in the future as well as support for non-uniform per-voxel defined extinction values which would also enable some great effects.

**Comment by engineer1109** [comment]
@CirilBohak The exposure render. I have migrated it into Linux.
https://github.com/engineer1109/exposure-render-for-Linux.git
I am trying to migrate to GLSL.

**Comment by CirilBohak** [comment]
That's great. Good work. I will check it out in more detail.

It would be interesting to see its implementation in Vulkan and/or WebGPU :)

**Comment by CirilBohak** [comment]
@engineer1109: I have also seen, you are learning Vulkan. You might check our lightweight Vulkan framework [Logi](https://github.com/UL-FRI-LGM/Logi), which makes a lot of things easier (e.g., GPU memory manager via Vulkan Memory Allocator, Object-oriented approach, and automatic managing of object hierarchy memory allocation/dealocation.
